[java]
disabled = true

[kotlin]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = true

[gcloud]
disabled = true

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 200
